source "https://rubygems.org"

gem "base64" # Required by Jekyll's safe_yaml on Ruby 3.4+.
gem "bigdecimal" # Required by Liquid on Ruby 3.4+.
gem "jekyll", "~> 3.10"
gem "jekyll-relative-links", "~> 0.6.0"
gem "kramdown-parser-gfm", "~> 1.1"
